### ISSUE TITLE
Julius Caesar - Program - Initial details

### ISSUE THREAD

**Issue by pigsflew** [Worlds-Elsewhere/worlds-elsewhere.com#26]
Create a program page for Julius Caesar.

![Promo image](https://media.discordapp.net/attachments/763876547416817695/812862943854329856/JCFBEvent3.png)

Details:

```yaml
show:
  title: William Shakespeare's *Julius Caesar*
  text:
    promo: TBD
    description: TBD
  time:
    start:  2021-03-20 19:00 -0400
  crew:
    director: Meryl Federman
    assistant-director: Bex Silberfein
    producer: David Kowarsky
```

Initial program page to include `details & promo`, `description`, `artistic_statement`, `support` section.
